# Generated by Django 5.0 on 2023-12-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eniola', '0002_remove_userformgrabber_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformgrabber',
            name='message',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
