# Generated by Django 5.0 on 2023-12-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eniola', '0004_alter_userformgrabber_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformgrabber',
            name='message',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
