# Generated by Django 5.0 on 2023-12-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eniola', '0005_alter_userformgrabber_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformgrabber',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
